import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * Regression test for the production bug where /api/geo-audits returned
 * an empty-body 500 because ensureGeoAuditsSchema's CREATE TABLE
 * declared `brand_id UUID NOT NULL ... REFERENCES brands(id)` while
 * `brands.id` is TEXT (generated by uid() = `Date.now().toString(36) +
 * crypto.randomBytes(6).toString('hex')`, NOT a UUID).
 *
 * Postgres rejected the CREATE TABLE with:
 *   ERROR: foreign key constraint cannot be implemented
 *   DETAIL: Key columns "brand_id" and "id" are of incompatible types: uuid and text.
 *
 * The throw bubbled out of the GET handler (which had no try/catch),
 * Next.js returned 500 with empty body, and the page rendered
 * "Couldn't load audits - Failed to load (HTTP 500)".
 *
 * This test asserts the column-type contract directly against the SQL
 * `ensureGeoAuditsSchema` emits, so a future refactor can't reintroduce
 * the type-mismatch silently. (Mocked queries - we assert the SQL
 * string, not the DB outcome.)
 */

type QueryFn = (sql: string, params?: unknown[]) => Promise<{ rows: unknown[]; rowCount?: number | null }>;
const queryMock = vi.fn<Parameters<QueryFn>, ReturnType<QueryFn>>(async () => ({ rows: [] }));

vi.mock('../src/lib/db', () => ({
  pool: { query: (...args: Parameters<QueryFn>) => queryMock(...args) },
}));

beforeEach(async () => {
  queryMock.mockReset();
  queryMock.mockImplementation(async () => ({ rows: [] }));
  // Force re-import so the schemaEnsured cache inside the lib is reset
  // between tests. Each test sees a fresh module instance.
  vi.resetModules();
});
afterEach(() => { vi.clearAllMocks(); });

describe('ensureGeoAuditsSchema - column type contract (#bug-fix)', () => {
  it('declares geo_audits.user_id as TEXT (matches users.id; NOT UUID)', async () => {
    const { ensureGeoAuditsSchema } = await import('../src/lib/geo-audits');
    await ensureGeoAuditsSchema();
    const auditCreate = queryMock.mock.calls.find(
      ([sql]) => /CREATE TABLE IF NOT EXISTS geo_audits\b/i.test(sql),
    );
    expect(auditCreate).toBeDefined();
    const sql = auditCreate![0];
    expect(sql).toMatch(/user_id\s+TEXT\s+NOT NULL/i);
    expect(sql).not.toMatch(/user_id\s+UUID/i);
  });

  it('declares geo_audits.brand_id as TEXT (matches brands.id; NOT UUID - the FK type-mismatch that caused the 500)', async () => {
    const { ensureGeoAuditsSchema } = await import('../src/lib/geo-audits');
    await ensureGeoAuditsSchema();
    const auditCreate = queryMock.mock.calls.find(
      ([sql]) => /CREATE TABLE IF NOT EXISTS geo_audits\b/i.test(sql),
    );
    expect(auditCreate).toBeDefined();
    const sql = auditCreate![0];
    expect(sql).toMatch(/brand_id\s+TEXT\s+NOT NULL/i);
    expect(sql).not.toMatch(/brand_id\s+UUID/i);
  });

  it('keeps the FK to brands(id) ON DELETE CASCADE so cleanup still works', async () => {
    const { ensureGeoAuditsSchema } = await import('../src/lib/geo-audits');
    await ensureGeoAuditsSchema();
    const auditCreate = queryMock.mock.calls.find(
      ([sql]) => /CREATE TABLE IF NOT EXISTS geo_audits\b/i.test(sql),
    );
    expect(auditCreate![0]).toMatch(
      /FOREIGN KEY\s*\(\s*brand_id\s*\)\s*REFERENCES\s+brands\s*\(\s*id\s*\)\s+ON DELETE CASCADE/i,
    );
  });

  it('emits the CHECK constraint on status (matches active_runs convention; no native ENUM)', async () => {
    const { ensureGeoAuditsSchema } = await import('../src/lib/geo-audits');
    await ensureGeoAuditsSchema();
    const auditCreate = queryMock.mock.calls.find(
      ([sql]) => /CREATE TABLE IF NOT EXISTS geo_audits\b/i.test(sql),
    );
    expect(auditCreate![0]).toMatch(/CHECK\s*\(\s*status IN \(\s*'queued'\s*,\s*'running'\s*,\s*'done'\s*,\s*'failed'\s*,\s*'cancelled'\s*\)\s*\)/i);
  });
});
