/**
 * Branded PDF generator for a saved NAP audit - a client-facing deliverable.
 * Returns a PDFKit document with doc.end() already called; the route buffers it
 * into a Response (same pattern as lib/pdf-report.ts).
 */
import PDFDocument from 'pdfkit';
import type { NapAuditRecord } from '@/lib/nap-audits';

const BRAND = '#5B5BD6';
const INK = '#1a1a2e';
const MUTE = '#64748b';
const LINE = '#e5e7eb';

function scoreColor(score: number): string {
  if (score >= 85) return '#16a34a';
  if (score >= 60) return '#ca8a04';
  return '#dc2626';
}

function fmtDate(iso: string | null): string {
  if (!iso) return '-';
  const d = new Date(iso);
  return isNaN(d.getTime()) ? '-' : d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

export function generateNapAuditPdf(audit: NapAuditRecord): PDFKit.PDFDocument {
  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  const left = doc.page.margins.left;
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // ── Header ──
  doc.fillColor(BRAND).fontSize(11).font('Helvetica-Bold').text('LIVESOV', left, 40);
  doc.fillColor(MUTE).fontSize(9).font('Helvetica').text('NAP Citation Audit', { align: 'right' });
  doc.moveDown(1.5);

  doc.fillColor(INK).fontSize(22).font('Helvetica-Bold').text(audit.label);
  const c = audit.canonical;
  const napLine = [c.name, c.street, c.suite, c.city, c.postcode, c.phone].filter(Boolean).join('  ·  ');
  doc.moveDown(0.3);
  doc.fillColor(MUTE).fontSize(10).font('Helvetica').text(napLine);
  doc.moveDown(0.2);
  doc.fillColor(MUTE).fontSize(9).text(`Last run ${fmtDate(audit.lastRunAt)}  ·  Generated ${fmtDate(new Date().toISOString())}`);
  doc.moveDown(1);

  // ── Score + summary ──
  const score = audit.score ?? 0;
  doc.fillColor(scoreColor(score)).fontSize(40).font('Helvetica-Bold').text(`${score}`, left, doc.y, { continued: true });
  doc.fillColor(MUTE).fontSize(14).font('Helvetica').text(' /100 consistency');
  doc.moveDown(0.6);

  const s = audit.summary;
  if (s) {
    const stats = [
      ['Citations', s.total],
      ['Clean', s.clean],
      ['With issues', s.withIssues],
      ['Dead links', s.deadLinks],
      ['Duplicates', s.duplicateListings],
    ];
    doc.fontSize(10).font('Helvetica');
    let x = left;
    const cellW = width / stats.length;
    const y = doc.y;
    for (const [k, v] of stats) {
      doc.fillColor(INK).font('Helvetica-Bold').fontSize(16).text(String(v), x, y, { width: cellW });
      doc.fillColor(MUTE).font('Helvetica').fontSize(8).text(String(k), x, y + 20, { width: cellW });
      x += cellW;
    }
    doc.y = y + 40;
  }
  doc.moveDown(0.5);

  // ── Duplicate listings ──
  if (audit.duplicates.length > 0) {
    section(doc, 'Possible duplicate listings', left, width);
    doc.fontSize(9).font('Helvetica');
    for (const g of audit.duplicates) {
      doc.fillColor(g.conflicting ? '#b91c1c' : INK).font('Helvetica-Bold').text(
        `${g.domain} - ${g.urls.length} listings${g.conflicting ? ' (conflicting NAP)' : ''}`,
      );
    }
    doc.moveDown(0.6);
  }

  // ── Results table ──
  section(doc, 'Citation results', left, width);
  const cols = [
    { k: 'Citation', w: 0.42 },
    { k: 'Score', w: 0.1 },
    { k: 'Name', w: 0.12 },
    { k: 'Phone', w: 0.12 },
    { k: 'Issues', w: 0.24 },
  ];
  const rowY0 = doc.y;
  let cx = left;
  doc.fontSize(8).font('Helvetica-Bold').fillColor(MUTE);
  for (const col of cols) {
    doc.text(col.k.toUpperCase(), cx, rowY0, { width: col.w * width });
    cx += col.w * width;
  }
  doc.moveTo(left, rowY0 + 12).lineTo(left + width, rowY0 + 12).strokeColor(LINE).stroke();
  doc.y = rowY0 + 16;

  doc.fontSize(8).font('Helvetica');
  for (const r of audit.results) {
    if (doc.y > doc.page.height - 70) {
      doc.addPage();
      doc.y = doc.page.margins.top;
    }
    const y = doc.y;
    cx = left;
    const host = r.url.replace(/^https?:\/\//, '');
    doc.fillColor(INK).text(host.length > 44 ? host.slice(0, 43) + '…' : host, cx, y, { width: cols[0].w * width });
    cx += cols[0].w * width;
    doc.fillColor(r.reachable ? scoreColor(r.matchScore) : MUTE).text(r.reachable ? String(r.matchScore) : '-', cx, y, { width: cols[1].w * width });
    cx += cols[1].w * width;
    doc.fillColor(MUTE).text(r.fields.name.status, cx, y, { width: cols[2].w * width });
    cx += cols[2].w * width;
    doc.text(r.fields.phone.status, cx, y, { width: cols[3].w * width });
    cx += cols[3].w * width;
    doc.fillColor(r.tags.length ? '#b91c1c' : '#16a34a').text(r.tags.length ? r.tags.join(', ') : 'consistent', cx, y, { width: cols[4].w * width });
    doc.moveDown(0.4);
  }

  // ── Footer ──
  doc.fontSize(8).fillColor(MUTE).font('Helvetica').text(
    'Generated by Livesov - livesov.com/tools/nap-verification',
    left,
    doc.page.height - 40,
    { width, align: 'center' },
  );

  doc.end();
  return doc;
}

function section(doc: PDFKit.PDFDocument, title: string, left: number, width: number): void {
  if (doc.y > doc.page.height - 90) {
    doc.addPage();
    doc.y = doc.page.margins.top;
  }
  doc.moveDown(0.4);
  doc.fillColor(INK).fontSize(12).font('Helvetica-Bold').text(title, left, doc.y);
  doc.moveTo(left, doc.y + 2).lineTo(left + width, doc.y + 2).strokeColor(LINE).stroke();
  doc.moveDown(0.5);
}
