import { NextRequest } from 'next/server';
import { rateLimit, rateLimitResponse } from '@/lib/rate-limit';
import { safeFetch, SSRFError } from '@/lib/safe-fetch';
import { logError, serverError } from '@/lib/api-error';

interface SitemapUrl {
  loc: string;
  lastmod?: string;
}

function parseSitemap(xml: string): { urls: SitemapUrl[]; sitemaps: string[] } {
  const urls: SitemapUrl[] = [];
  const sitemaps: string[] = [];

  const urlBlocks = xml.match(/<url>[\s\S]*?<\/url>/g) || [];
  for (const block of urlBlocks) {
    const loc = block.match(/<loc>([\s\S]*?)<\/loc>/)?.[1]?.trim();
    const lastmod = block.match(/<lastmod>([\s\S]*?)<\/lastmod>/)?.[1]?.trim();
    if (loc) urls.push({ loc, lastmod });
  }

  const sitemapBlocks = xml.match(/<sitemap>[\s\S]*?<\/sitemap>/g) || [];
  for (const block of sitemapBlocks) {
    const loc = block.match(/<loc>([\s\S]*?)<\/loc>/)?.[1]?.trim();
    if (loc) sitemaps.push(loc);
  }

  return { urls, sitemaps };
}

async function fetchSitemap(url: string): Promise<string> {
  const res = await safeFetch(url, { timeoutMs: 10_000, maxBytes: 5 * 1024 * 1024 });
  if (!res.ok) throw new Error(`Sitemap returned HTTP ${res.status}`);
  return await res.text();
}

function categorize(path: string): string {
  const p = path.toLowerCase();
  if (p === '/' || p === '') return 'Home';
  if (p.startsWith('/blog')) return 'Blog';
  if (p.startsWith('/docs') || p.startsWith('/documentation')) return 'Documentation';
  if (p.startsWith('/product') || p.startsWith('/features')) return 'Product';
  if (p.startsWith('/pricing')) return 'Pricing';
  if (p.startsWith('/about') || p.startsWith('/team') || p.startsWith('/company')) return 'Company';
  if (p.startsWith('/contact')) return 'Contact';
  if (p.startsWith('/use-cases') || p.startsWith('/solutions')) return 'Use Cases';
  if (p.startsWith('/tools')) return 'Tools';
  if (p.startsWith('/integrations')) return 'Integrations';
  if (p.startsWith('/vs') || p.startsWith('/alternatives') || p.startsWith('/compare')) return 'Comparisons';
  return 'Other';
}

function buildLlmsTxt(domain: string, urls: SitemapUrl[]): string {
  const host = new URL(domain).host;
  const groups = new Map<string, SitemapUrl[]>();
  for (const u of urls) {
    let path = '/';
    try {
      path = new URL(u.loc).pathname;
    } catch {
      continue;
    }
    const cat = categorize(path);
    if (!groups.has(cat)) groups.set(cat, []);
    groups.get(cat)!.push(u);
  }

  const order = ['Home', 'Product', 'Pricing', 'Tools', 'Use Cases', 'Integrations', 'Comparisons', 'Documentation', 'Blog', 'Company', 'Contact', 'Other'];
  const sortedKeys = order.filter((k) => groups.has(k));

  const lines: string[] = [];
  lines.push(`# ${host}`);
  lines.push('');
  lines.push(`> Generated by Livesov llms.txt Generator (https://livesov.com/tools/llms-txt-generator)`);
  lines.push('');
  for (const key of sortedKeys) {
    lines.push(`## ${key}`);
    lines.push('');
    const items = groups.get(key)!.slice(0, 50);
    for (const u of items) {
      const path = new URL(u.loc).pathname;
      const title = path === '/' ? host : path.replace(/^\//, '').replace(/\/$/, '').split('/').pop() || path;
      const pretty = title.replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
      lines.push(`- [${pretty}](${u.loc})`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function normalizeDomain(input: string): string {
  let d = input.trim();
  if (!/^https?:\/\//i.test(d)) d = `https://${d}`;
  const url = new URL(d);
  return `${url.protocol}//${url.host}`;
}

export async function POST(req: NextRequest) {
  try {
    const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'unknown';
    const { allowed, retryAfter } = await rateLimit(`llms-txt-gen:${ip}`, 60 * 60 * 1000, 10);
    if (!allowed) return rateLimitResponse(retryAfter);

    const body = await req.json().catch(() => ({}));
    const rawDomain = typeof body?.domain === 'string' ? body.domain : '';
    if (!rawDomain || rawDomain.length > 500) {
      return Response.json({ error: 'Domain is required (max 500 chars).' }, { status: 400 });
    }

    let domain: string;
    try {
      domain = normalizeDomain(rawDomain);
    } catch {
      return Response.json({ error: 'Invalid domain.' }, { status: 400 });
    }

    const triedSitemaps: string[] = [];
    const collected: SitemapUrl[] = [];
    const queue = [`${domain}/sitemap.xml`, `${domain}/sitemap_index.xml`];
    const seen = new Set<string>();
    let fetchedAny = false;

    while (queue.length && triedSitemaps.length < 8) {
      const next = queue.shift()!;
      if (seen.has(next)) continue;
      seen.add(next);
      triedSitemaps.push(next);
      try {
        const xml = await fetchSitemap(next);
        fetchedAny = true;
        const parsed = parseSitemap(xml);
        collected.push(...parsed.urls);
        for (const sm of parsed.sitemaps) {
          if (!seen.has(sm) && triedSitemaps.length + queue.length < 8) queue.push(sm);
        }
        if (collected.length >= 500) break;
      } catch (err) {
        if (err instanceof SSRFError) {
          return Response.json({ error: 'That domain is not reachable from our servers.' }, { status: 400 });
        }
        // try next sitemap
      }
    }

    if (!fetchedAny || collected.length === 0) {
      return Response.json({
        error: `No sitemap found at ${triedSitemaps.join(' or ')}. Add a sitemap.xml then try again.`,
      }, { status: 404 });
    }

    const trimmed = collected.slice(0, 500);
    const llmsTxt = buildLlmsTxt(domain, trimmed);

    return Response.json({
      domain,
      urlCount: trimmed.length,
      sitemapsCrawled: triedSitemaps.length,
      llmsTxt,
    });
  } catch (error) {
    logError('tools.llms_txt_generator.failed', error);
    return serverError({ message: 'Failed to generate llms.txt. Please try again.' });
  }
}
